AAPL: 1
ADAUSD: 1
AIRF: 1
ALVG: 1
AMZN: 1
AUDCAD: 30
AUDCHF: 30
AUDJPY: 30
AUDNZD: 20
AUDUSD: 30
AUS200.cash: 15
BABA: 1
BAC: 1
BAYGn: 1
BTCUSD: 1
CADCHF: 30 
CADJPY: 30 
CHFJPY: 30
COCOA.c: 1
COFFEE.c: 1
COTTON.c: 1
CORN.c: 1
DASHUSD: 1
DBKGn: 1
DOGEUSD: 1
DOTUSD: 1
DXY.cash: 5
ETHUSD: 1
EU50.cash: 15
EURAUD: 30
EURCAD: 30
EURCHF: 30
EURCZK: 20
EURGBP: 30
EURHUF: 20
EURJPY: 30
EURNZD: 20
EURUSD: 30
EURNOK: 20
EURPLN: 20
FRA40.cash: 15
GBPAUD: 30
GBPCAD: 30
GBPCHF: 30
GBPJPY: 30
GBPNZD: 20
GBPUSD: 30
GER40.cash: 15
GOOG: 1
HEATOIL.c: 9
HK50.cash: 9
IBE: 1
JP225.cash: 15
LTCUSD: 1
LVMH: 1
META: 1
MSFT: 1
N25.cash: 9
NATGAS.cash: 9
NEOUSD: 1
NFLX: 1
NVDA: 1
NZDCAD: 20
NZDCHF: 20
NZDJPY: 20
NZDUSD: 20
PFE: 1
RACE: 1
SOYBEAN.c: 1
SPN35.cash: 9
SUGAR.c: 1
T: 1
TSLA: 1
UK100.cash: 15
UKOIL.cash: 9
US100.cash: 15
US2000.cash: 9
US30.cash: 15
US500.cash: 15
USDCAD: 30
USDCHF: 30 
USDCNH: 20
USDJPY: 30
USDCZK: 20
USDHKD: 20
USDHUF: 20
USDILS: 20
USDMXN: 20
USDNOK: 20
USDPLN: 20
USDSGD: 20
USDZAR: 20
USDSEK: 20
USDHUF: 20
USOIL.cash: 9
V: 1
VOWG_p: 1
WHEAT.c: 1
WMT: 1
XAGUSD: 9
XAGEUR: 9
XAGAUD: 9
XAUUSD: 9
XAUEUR: 9
XAUAUD: 9
XPDUSD: 9
XPTUSD: 9
XCUUSD: 9
XMRUSD: 1
XRPUSD: 1
ZM: 1
